In [1]:
import pandas as pd

# Import datasets and validate

In [2]:
path_failures = '../dataset/wind-farm-1-failures-training.csv'
path_dataset = '../dataset/wind-farm-1-signals-training.json'

## dataset

In [3]:
df = pd.read_json(path_dataset)
df = pd.DataFrame.from_dict(df['fields'].tolist())
df.head()

,grd_prod_pwr_min,gen_rpm_avg,blds_pitchangle_max,grd_prod_pwr_avg,amb_winddir_abs_avg,gen_bear_temp_avg,amb_windspeed_min,grd_prod_reactpwr_max,grd_prod_curphse1_avg,grd_prod_pwr_max,...,gear_oil_temp_avg,gen_rpm_min,grd_prod_voltphse1_avg,turbine_id,grd_prod_psblepwr_std,grd_prod_cosphi_avg,prod_latestavg_actpwrgen0,prod_latestavg_actpwrgen1,prod_latestavg_actpwrgen2,rtr_rpm_std
0,154.1,1270.9,0.9,246.1,199.1,42.0,2.6,-72.5,197.0,368.9,...,48,1233.3,400.7,T11,51.7,0.9,0,41059.0,0,0.2
1,-17.8,1248.5,0.9,62.5,201.5,42.0,1.6,0.1,78.8,178.4,...,43,1232.8,400.7,T06,36.7,0.6,0,10465.0,0,0.1
2,-33.5,1249.0,4.5,26.2,206.1,41.0,0.5,13.2,46.5,118.4,...,44,1226.1,401.6,T01,31.9,0.7,-107,4420.0,0,0.1
3,46.0,1272.0,0.6,198.4,220.1,40.0,1.8,-72.7,161.5,349.0,...,43,1234.3,402.0,T09,61.5,0.9,0,33173.0,0,0.2
4,-11.5,1254.9,2.5,112.7,178.7,41.0,0.9,0.2,107.8,277.3,...,45,1229.5,402.2,T07,74.9,0.8,0,18831.0,0,0.1

In [4]:
# make all columns as lowercase
df.columns = [col.lower() for col in df.columns]

# make timestamp, turbine_id as first columns
cols = df.columns.tolist()
first_cols = ['timestamp','turbine_id']
[cols.remove(c) for c in first_cols]
cols = first_cols + cols
df = df[cols].copy()

# make timestamp as datetime type
df['timestamp'] = pd.to_datetime(df['timestamp'])
print(f'Dimensions of the dataset: {df.shape}')
df.head(10)

Dimensions of the dataset: (434145, 83)

,timestamp,turbine_id,grd_prod_pwr_min,gen_rpm_avg,blds_pitchangle_max,grd_prod_pwr_avg,amb_winddir_abs_avg,gen_bear_temp_avg,amb_windspeed_min,grd_prod_reactpwr_max,...,blds_pitchangle_std,gear_oil_temp_avg,gen_rpm_min,grd_prod_voltphse1_avg,grd_prod_psblepwr_std,grd_prod_cosphi_avg,prod_latestavg_actpwrgen0,prod_latestavg_actpwrgen1,prod_latestavg_actpwrgen2,rtr_rpm_std
0,2016-01-01 00:00:00+00:00,T11,154.1,1270.9,0.9,246.1,199.1,42.0,2.6,-72.5,...,0.3,48,1233.3,400.7,51.7,0.9,0,41059.0,0,0.2
1,2016-01-01 00:00:00+00:00,T06,-17.8,1248.5,0.9,62.5,201.5,42.0,1.6,0.1,...,0.5,43,1232.8,400.7,36.7,0.6,0,10465.0,0,0.1
2,2016-01-01 00:00:00+00:00,T01,-33.5,1249.0,4.5,26.2,206.1,41.0,0.5,13.2,...,0.9,44,1226.1,401.6,31.9,0.7,-107,4420.0,0,0.1
3,2016-01-01 00:00:00+00:00,T09,46.0,1272.0,0.6,198.4,220.1,40.0,1.8,-72.7,...,0.5,43,1234.3,402.0,61.5,0.9,0,33173.0,0,0.2
4,2016-01-01 00:00:00+00:00,T07,-11.5,1254.9,2.5,112.7,178.7,41.0,0.9,0.2,...,0.8,45,1229.5,402.2,74.9,0.8,0,18831.0,0,0.1
5,2016-01-01 00:10:00+00:00,T09,60.7,1321.4,0.5,231.1,218.7,40.0,2.0,-76.7,...,0.6,43,1239.7,401.8,86.4,0.9,0,38381.0,0,0.4
6,2016-01-01 00:10:00+00:00,T07,-1.9,1251.9,0.9,95.5,191.8,42.0,1.4,0.2,...,0.5,45,1233.4,401.9,36.9,0.7,0,15865.0,0,0.1
7,2016-01-01 00:10:00+00:00,T06,-32.1,1154.1,49.6,8.9,219.1,42.0,1.3,16.4,...,8.9,42,203.9,401.1,44.7,0.7,-734,2295.0,0,2.4
8,2016-01-01 00:10:00+00:00,T01,-38.2,999.7,59.6,10.1,217.4,41.0,0.4,1.8,...,14.7,44,93.3,401.9,24.7,0.7,-753,2488.0,0,4.0
9,2016-01-01 00:10:00+00:00,T11,191.3,1303.6,-0.8,304.7,207.5,43.0,1.7,-76.8,...,0.4,48,1239.8,400.4,54.8,1.0,0,50808.0,0,0.4

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 434145 entries, 0 to 434144
Data columns (total 83 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   timestamp                    434145 non-null  datetime64[ns, UTC]
 1   turbine_id                   434145 non-null  object
 2   grd_prod_pwr_min             434145 non-null  float64
 3   gen_rpm_avg                  434145 non-null  float64
 4   blds_pitchangle_max          434145 non-null  float64
 5   grd_prod_pwr_avg             434145 non-null  float64
 6   amb_winddir_abs_avg          434145 non-null  float64
 7   gen_bear_temp_avg            434138 non-null  float64
 8   amb_windspeed_min            434145 non-null  float64
 9   grd_prod_reactpwr_max        434145 non-null  float64
 10  grd_prod_curphse1_avg        434145 non-null  float64
 11  grd_prod_pwr_max             434145 non-null  float64
 12  grd_prod_pwr_std             434145 non-null  float64
 13  blds_pitchangle_min          434145 non-null  float64
 14  gen_phase2_temp_avg          434145 non-null  int64
 15  hvtrafo_phase1_temp_avg      434145 non-null  int64
 16  rtr_rpm_max                  434145 non-null  float64
 17  gear_bear_temp_avg           434145 non-null  int64
 18  grd_prod_psblepwr_max        434145 non-null  float64
 19  grd_prod_psbleind_avg        434145 non-null  float64
 20  grd_prod_psblepwr_avg        434145 non-null  float64
 21  grd_prod_psbleind_min        434145 non-null  float64
 22  amb_winddir_relative_avg     434145 non-null  float64
 23  grd_rtrinvphase2_temp_avg    434145 non-null  int64
 24  hvtrafo_phase3_temp_avg      434145 non-null  int64
 25  grd_prod_psblepwr_min        434145 non-null  float64
 26  grd_busbar_temp_avg          434145 non-null  int64
 27  grd_prod_voltphse3_avg       434145 non-null  float64
 28  amb_windspeed_avg            434145 non-null  float64
 29  grd_prod_psblecap_min        434145 non-null  float64
 30  grd_prod_psbleind_max        434145 non-null  float64
 31  amb_windspeed_std            434145 non-null  float64
 32  grd_rtrinvphase1_temp_avg    434145 non-null  int64
 33  rtr_rpm_avg                  434145 non-null  float64
 34  grd_prod_reactpwr_min        434145 non-null  float64
 35  cont_vcp_wtrtemp_avg         434145 non-null  int64
 36  prod_latestavg_totactpwr     434145 non-null  float64
 37  cont_vcp_chokcoiltemp_avg    434145 non-null  int64
 38  gen_slipring_temp_avg        434145 non-null  int64
 39  grd_prod_reactpwr_std        434145 non-null  float64
 40  spin_temp_avg                434145 non-null  int64
 41  grd_prod_psblecap_avg        434145 non-null  float64
 42  hvtrafo_phase2_temp_avg      434145 non-null  int64
 43  nac_temp_avg                 434145 non-null  int64
 44  grd_prod_curphse3_avg        434145 non-null  float64
 45  grd_rtrinvphase3_temp_avg    434145 non-null  int64
 46  grd_prod_psblecap_std        434145 non-null  float64
 47  gen_phase3_temp_avg          434145 non-null  int64
 48  cont_hub_temp_avg            434145 non-null  int64
 49  prod_latestavg_totreactpwr   434145 non-null  int64
 50  gen_phase1_temp_avg          434145 non-null  int64
 51  grd_prod_curphse2_avg        434145 non-null  float64
 52  gen_rpm_std                  434145 non-null  float64
 53  grd_prod_psbleind_std        434145 non-null  float64
 54  rtr_rpm_min                  434145 non-null  float64
 55  grd_prod_psblecap_max        434145 non-null  float64
 56  prod_latestavg_reactpwrgen2  434145 non-null  int64
 57  nac_direction_avg            434145 non-null  float64
 58  blds_pitchangle_avg          434145 non-null  float64
 59  amb_windspeed_est_avg        434145 non-null  float64
 60  gen_rpm_max                  434145 non-null  float64
 61  gen_bear2_temp_avg           434145 non-null  int64
 62  grd_prod_voltphse2_avg       434145 non-null  float64
 63  hyd_oil_temp_avg             434145 non-null  int64
 64  cont_top_temp_avg            434145 non-null  int64
 65  prod_latestavg_reactpwrgen1  434145 non-null  int64
 66  prod_latestavg_reactpwrgen0  434145 non-null  int64
 67  grd_prod_reactpwr_avg        434145 non-null  float64
 68  cont_vcp_temp_avg            434145 non-null  int64
 69  amb_windspeed_max            434145 non-null  float64
 70  grd_prod_freq_avg            434145 non-null  float64
 71  grd_inverterphase1_temp_avg  434145 non-null  int64
 72  amb_temp_avg                 434145 non-null  int64
 73  blds_pitchangle_std          434145 non-null  float64
 74  gear_oil_temp_avg            434145 non-null  int64
 75  gen_rpm_min                  434145 non-null  float64
 76  grd_prod_voltphse1_avg       434145 non-null  float64
 77  grd_prod_psblepwr_std        434145 non-null  float64
 78  grd_prod_cosphi_avg          434138 non-null  float64
 79  prod_latestavg_actpwrgen0    434145 non-null  int64
 80  prod_latestavg_actpwrgen1    434145 non-null  float64
 81  prod_latestavg_actpwrgen2    434145 non-null  int64
 82  rtr_rpm_std                  434145 non-null  float64
dtypes: datetime64[ns, UTC](1), float64(51), int64(30), object(1)
memory usage: 274.9+ MB

## failures

In [6]:
failures = pd.read_csv(path_failures, sep=';')
failures.columns = [col.lower() for col in failures.columns]
failures['timestamp'] = pd.to_datetime(failures['timestamp'])
print(f'Dimensions of the dataset: {failures.shape}')
failures

Dimensions of the dataset: (23, 4)

,turbine_id,component,timestamp,remarks
0,T11,GENERATOR,2016-03-03 19:00:00+00:00,Electric circuit error in generator
1,T06,HYDRAULIC_GROUP,2016-04-04 18:53:00+00:00,Error in pitch regulation
2,T07,GENERATOR_BEARING,2016-04-30 12:40:00+00:00,High temperature in generator bearing (replace...
3,T09,GENERATOR_BEARING,2016-06-07 16:59:00+00:00,High tempemperature generator bearing
4,T07,TRANSFORMER,2016-07-10 03:46:00+00:00,High temperature transformer
5,T06,GENERATOR,2016-07-11 19:48:00+00:00,Generator replaced
6,T01,GEARBOX,2016-07-18 02:10:00+00:00,Gearbox pump damaged
7,T06,GENERATOR,2016-07-24 17:01:00+00:00,Generator temperature sensor failure
8,T09,GENERATOR_BEARING,2016-08-22 18:25:00+00:00,High temperature generator bearing
9,T07,TRANSFORMER,2016-08-23 02:21:00+00:00,High temperature transformer. Transformer refr...
10,T06,GENERATOR,2016-09-04 08:08:00+00:00,High temperature generator error
11,T06,GENERATOR,2016-10-02 17:08:00+00:00,Refrigeration system and temperature sensors i...
12,T09,GEARBOX,2016-10-11 08:06:00+00:00,Gearbox repaired
13,T09,GENERATOR_BEARING,2016-10-17 09:19:00+00:00,Generator bearings replaced
14,T11,HYDRAULIC_GROUP,2016-10-17 17:44:00+00:00,Hydraulic group error in the brake circuit
15,T06,GENERATOR,2016-10-27 16:26:00+00:00,Generator replaced
16,T09,GENERATOR_BEARING,2017-01-25 12:55:00+00:00,Generator bearings replaced
17,T11,HYDRAULIC_GROUP,2017-04-26 18:06:00+00:00,Hydraulic group error in the brake circuit
18,T07,HYDRAULIC_GROUP,2017-06-17 11:35:00+00:00,Oil leakage in Hub
19,T01,TRANSFORMER,2017-08-11 13:14:00+00:00,Transformer fan damaged
20,T06,HYDRAULIC_GROUP,2017-08-19 09:47:00+00:00,Oil leakage in Hub
21,T07,GENERATOR_BEARING,2017-08-20 06:08:00+00:00,Generator bearings damaged
22,T07,GENERATOR,2017-08-21 14:47:00+00:00,Generator damaged

In [7]:
failures.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23 entries, 0 to 22
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   turbine_id  23 non-null     object
 1   component   23 non-null     object
 2   timestamp   23 non-null     datetime64[ns, UTC]
 3   remarks     23 non-null     object
dtypes: datetime64[ns, UTC](1), object(3)
memory usage: 864.0+ bytes

## merging datasets

In [8]:
df_merged = df.merge(failures, how='outer', on=['timestamp', 'turbine_id'])

In [9]:
# add failure column
df_merged.loc[:,['failure']] = 0
df_merged.loc[~df_merged['component'].isnull(),['failure']] = 1

In [10]:
df_merged['turbine_id'].unique()

array(['T11', 'T06', 'T01', 'T09', 'T07'], dtype=object)

so there are five types of Turbines, so I'll analyse each of them separetely

## First Analysis

In [11]:
df_merged.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 434166 entries, 0 to 434165
Data columns (total 86 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   timestamp                    434166 non-null  datetime64[ns, UTC]
 1   turbine_id                   434166 non-null  object
 2   grd_prod_pwr_min             434145 non-null  float64
 3   gen_rpm_avg                  434145 non-null  float64
 4   blds_pitchangle_max          434145 non-null  float64
 5   grd_prod_pwr_avg             434145 non-null  float64
 6   amb_winddir_abs_avg          434145 non-null  float64
 7   gen_bear_temp_avg            434138 non-null  float64
 8   amb_windspeed_min            434145 non-null  float64
 9   grd_prod_reactpwr_max        434145 non-null  float64
 10  grd_prod_curphse1_avg        434145 non-null  float64
 11  grd_prod_pwr_max             434145 non-null  float64
 12  grd_prod_pwr_std             434145 non-null  float64
 13  blds_pitchangle_min          434145 non-null  float64
 14  gen_phase2_temp_avg          434145 non-null  float64
 15  hvtrafo_phase1_temp_avg      434145 non-null  float64
 16  rtr_rpm_max                  434145 non-null  float64
 17  gear_bear_temp_avg           434145 non-null  float64
 18  grd_prod_psblepwr_max        434145 non-null  float64
 19  grd_prod_psbleind_avg        434145 non-null  float64
 20  grd_prod_psblepwr_avg        434145 non-null  float64
 21  grd_prod_psbleind_min        434145 non-null  float64
 22  amb_winddir_relative_avg     434145 non-null  float64
 23  grd_rtrinvphase2_temp_avg    434145 non-null  float64
 24  hvtrafo_phase3_temp_avg      434145 non-null  float64
 25  grd_prod_psblepwr_min        434145 non-null  float64
 26  grd_busbar_temp_avg          434145 non-null  float64
 27  grd_prod_voltphse3_avg       434145 non-null  float64
 28  amb_windspeed_avg            434145 non-null  float64
 29  grd_prod_psblecap_min        434145 non-null  float64
 30  grd_prod_psbleind_max        434145 non-null  float64
 31  amb_windspeed_std            434145 non-null  float64
 32  grd_rtrinvphase1_temp_avg    434145 non-null  float64
 33  rtr_rpm_avg                  434145 non-null  float64
 34  grd_prod_reactpwr_min        434145 non-null  float64
 35  cont_vcp_wtrtemp_avg         434145 non-null  float64
 36  prod_latestavg_totactpwr     434145 non-null  float64
 37  cont_vcp_chokcoiltemp_avg    434145 non-null  float64
 38  gen_slipring_temp_avg        434145 non-null  float64
 39  grd_prod_reactpwr_std        434145 non-null  float64
 40  spin_temp_avg                434145 non-null  float64
 41  grd_prod_psblecap_avg        434145 non-null  float64
 42  hvtrafo_phase2_temp_avg      434145 non-null  float64
 43  nac_temp_avg                 434145 non-null  float64
 44  grd_prod_curphse3_avg        434145 non-null  float64
 45  grd_rtrinvphase3_temp_avg    434145 non-null  float64
 46  grd_prod_psblecap_std        434145 non-null  float64
 47  gen_phase3_temp_avg          434145 non-null  float64
 48  cont_hub_temp_avg            434145 non-null  float64
 49  prod_latestavg_totreactpwr   434145 non-null  float64
 50  gen_phase1_temp_avg          434145 non-null  float64
 51  grd_prod_curphse2_avg        434145 non-null  float64
 52  gen_rpm_std                  434145 non-null  float64
 53  grd_prod_psbleind_std        434145 non-null  float64
 54  rtr_rpm_min                  434145 non-null  float64
 55  grd_prod_psblecap_max        434145 non-null  float64
 56  prod_latestavg_reactpwrgen2  434145 non-null  float64
 57  nac_direction_avg            434145 non-null  float64
 58  blds_pitchangle_avg          434145 non-null  float64
 59  amb_windspeed_est_avg        434145 non-null  float64
 60  gen_rpm_max                  434145 non-null  float64
 61  gen_bear2_temp_avg           434145 non-null  float64
 62  grd_prod_voltphse2_avg       434145 non-null  float64
 63  hyd_oil_temp_avg             434145 non-null  float64
 64  cont_top_temp_avg            434145 non-null  float64
 65  prod_latestavg_reactpwrgen1  434145 non-null  float64
 66  prod_latestavg_reactpwrgen0  434145 non-null  float64
 67  grd_prod_reactpwr_avg        434145 non-null  float64
 68  cont_vcp_temp_avg            434145 non-null  float64
 69  amb_windspeed_max            434145 non-null  float64
 70  grd_prod_freq_avg            434145 non-null  float64
 71  grd_inverterphase1_temp_avg  434145 non-null  float64
 72  amb_temp_avg                 434145 non-null  float64
 73  blds_pitchangle_std          434145 non-null  float64
 74  gear_oil_temp_avg            434145 non-null  float64
 75  gen_rpm_min                  434145 non-null  float64
 76  grd_prod_voltphse1_avg       434145 non-null  float64
 77  grd_prod_psblepwr_std        434145 non-null  float64
 78  grd_prod_cosphi_avg          434138 non-null  float64
 79  prod_latestavg_actpwrgen0    434145 non-null  float64
 80  prod_latestavg_actpwrgen1    434145 non-null  float64
 81  prod_latestavg_actpwrgen2    434145 non-null  float64
 82  rtr_rpm_std                  434145 non-null  float64
 83  component                    23 non-null      object
 84  remarks                      23 non-null      object
 85  failure                      434166 non-null  int64
dtypes: datetime64[ns, UTC](1), float64(81), int64(1), object(3)
memory usage: 288.2+ MB

In [12]:
df_merged['timestamp'].unique()

<DatetimeArray>
['2016-01-01 00:00:00+00:00', '2016-01-01 00:10:00+00:00',
 '2016-01-01 00:20:00+00:00', '2016-01-01 00:30:00+00:00',
 '2016-01-01 00:40:00+00:00', '2016-01-01 00:50:00+00:00',
 '2016-01-01 01:00:00+00:00', '2016-01-01 01:10:00+00:00',
 '2016-01-01 01:20:00+00:00', '2016-01-01 01:30:00+00:00',
 ...
 '2016-10-17 09:19:00+00:00', '2016-10-17 17:44:00+00:00',
 '2016-10-27 16:26:00+00:00', '2017-01-25 12:55:00+00:00',
 '2017-04-26 18:06:00+00:00', '2017-06-17 11:35:00+00:00',
 '2017-08-11 13:14:00+00:00', '2017-08-19 09:47:00+00:00',
 '2017-08-20 06:08:00+00:00', '2017-08-21 14:47:00+00:00']
Length: 87362, dtype: datetime64[ns, UTC]

I'll split the training data into training and test data, at first look, it seemms a good idea to make 2016 as training data and 2017 as test data

In [13]:
df_merged['turbine_id'].value_counts()

T11    87251
T07    87212
T09    87161
T01    87147
T06    85395
Name: turbine_id, dtype: int64

In [14]:
for turbine in df_merged['turbine_id'].unique():
    fails = df_merged.loc[(df_merged['turbine_id'] == turbine) & (~df_merged['component'].isnull()),['turbine_id','timestamp', 'component', 'remarks','failure']]
    print(f'************ For turbine {turbine} there were {fails.shape[0]} fails ************')
    display(fails)

************ For turbine T11 there were 3 fails ************

,turbine_id,timestamp,component,remarks,failure
434145,T11,2016-03-03 19:00:00+00:00,GENERATOR,Electric circuit error in generator,1
434157,T11,2016-10-17 17:44:00+00:00,HYDRAULIC_GROUP,Hydraulic group error in the brake circuit,1
434160,T11,2017-04-26 18:06:00+00:00,HYDRAULIC_GROUP,Hydraulic group error in the brake circuit,1

************ For turbine T06 there were 7 fails ************

,turbine_id,timestamp,component,remarks,failure
434146,T06,2016-04-04 18:53:00+00:00,HYDRAULIC_GROUP,Error in pitch regulation,1
434149,T06,2016-07-11 19:48:00+00:00,GENERATOR,Generator replaced,1
434150,T06,2016-07-24 17:01:00+00:00,GENERATOR,Generator temperature sensor failure,1
434153,T06,2016-09-04 08:08:00+00:00,GENERATOR,High temperature generator error,1
434154,T06,2016-10-02 17:08:00+00:00,GENERATOR,Refrigeration system and temperature sensors i...,1
434158,T06,2016-10-27 16:26:00+00:00,GENERATOR,Generator replaced,1
434163,T06,2017-08-19 09:47:00+00:00,HYDRAULIC_GROUP,Oil leakage in Hub,1

************ For turbine T01 there were 2 fails ************

,turbine_id,timestamp,component,remarks,failure
142065,T01,2016-07-18 02:10:00+00:00,GEARBOX,Gearbox pump damaged,1
434162,T01,2017-08-11 13:14:00+00:00,TRANSFORMER,Transformer fan damaged,1

************ For turbine T09 there were 5 fails ************

,turbine_id,timestamp,component,remarks,failure
434147,T09,2016-06-07 16:59:00+00:00,GENERATOR_BEARING,High tempemperature generator bearing,1
434151,T09,2016-08-22 18:25:00+00:00,GENERATOR_BEARING,High temperature generator bearing,1
434155,T09,2016-10-11 08:06:00+00:00,GEARBOX,Gearbox repaired,1
434156,T09,2016-10-17 09:19:00+00:00,GENERATOR_BEARING,Generator bearings replaced,1
434159,T09,2017-01-25 12:55:00+00:00,GENERATOR_BEARING,Generator bearings replaced,1

************ For turbine T07 there were 6 fails ************

,turbine_id,timestamp,component,remarks,failure
86729,T07,2016-04-30 12:40:00+00:00,GENERATOR_BEARING,High temperature in generator bearing (replace...,1
434148,T07,2016-07-10 03:46:00+00:00,TRANSFORMER,High temperature transformer,1
434152,T07,2016-08-23 02:21:00+00:00,TRANSFORMER,High temperature transformer. Transformer refr...,1
434161,T07,2017-06-17 11:35:00+00:00,HYDRAULIC_GROUP,Oil leakage in Hub,1
434164,T07,2017-08-20 06:08:00+00:00,GENERATOR_BEARING,Generator bearings damaged,1
434165,T07,2017-08-21 14:47:00+00:00,GENERATOR,Generator damaged,1

The dataset shows that aren't many fails in 2017

## Splitting the datasets for each turbine

In [15]:
for turbine in df_merged['turbine_id'].unique():
    df_turbine = df_merged.loc[(df_merged['turbine_id'] == turbine),:]
    df_turbine.to_json(f'../dataset/df_turbine_{turbine}.json') 
    print(f'************ Dataset saved for turbine {turbine}  ************')

************ Dataset saved for turbine T11  ************
************ Dataset saved for turbine T06  ************
************ Dataset saved for turbine T01  ************
************ Dataset saved for turbine T09  ************
************ Dataset saved for turbine T07  ************